### ISSUE TITLE
关于”select ret 0 没有找到WOW窗口"的问题

### ISSUE THREAD

**Issue by mrblue81** [whtiehack/wingui#13]
你好大佬，之前一直用你的wowjump，在重装了一次系统后（WOW在D盘没有重装），使用软件时会出现以下问题，
“2022/04/14 02:48:32 hwndArr [331092]
2022/04/14 02:48:32 select ret 0
2022/04/14 02:48:32 没有找到WOW窗口
”，我开始以为是注册表的问题，重装了游戏，仍然出现相同问题，新建一个“魔兽世界.TXT"的文档也依然无法检测。
查看了下代码，时隔太久发现也看不太明白了哈哈。不知是否可以帮忙解决下这个问题，感谢你的分享！

**Comment by mrblue81** [comment]
补充：实际上点击开始防掉线时，WOW窗口会跳出来，只是无法起作用

**Comment by whtiehack** [comment]
管理员权限打开程序试试. 
你这个日志已经检测到窗口了 ` hwndArr [331092]`  

` select ret 0` 这个显示你没有点wow窗口弹出来的确定.
