### ISSUE TITLE
wowjump Windows 10 企业版 LTSC 21H2环境下很容易未响应

### ISSUE THREAD

**Issue by xiao526** [whtiehack/wingui#17]
wowjump Windows 10 企业版 LTSC 21H2环境下很容易未响应
作者这个还更新吗？
我两台电脑 一台公司和家里的全部都是偶尔出现程序未响应状态导致掉线

**Comment by whtiehack** [comment]
https://github.com/whtiehack/wingui/releases/tag/v0.0.9

**Comment by xiao526** [comment]
我用的就是最新版 也没有用管理员权限打开 还是 程序执行的时候有几率程序未响应~~

**Comment by whtiehack** [comment]
https://github.com/whtiehack/wingui/releases/tag/v0.0.7
那你用这个老版试试
