### ISSUE TITLE
编译失败

### ISSUE THREAD

**Issue by lionios** [whtiehack/wingui#3]
你好，第一次接触Go，因为朋友发给我的wowjump失效了（9月12的版本），于是我尝试自己编译，最后弄到gcc failed，网上查说是因为32位写的代码无法在64位环境编译（不确定，不熟悉Go），希望能得到你的帮助。

**Comment by lionios** [comment]
现在问题已经进一步锁定到似乎是win7没有VB6的问题，网上查说是不兼容，但似乎有方法，正在尝试中

**Comment by lionios** [comment]
信息: 未找到 WinSxS 中的程序集。
				信息: 尝试在 C:\Windows\assembly\GAC_MSIL\Microsoft.Windows.Common-Controls\6.0.0.0_zh-CN_6595b64144ccf1df\Microsoft.Windows.Common-Controls.DLL 上探测指令清单。
				信息: 未找到区域性 zh-CN 的指令清单。

**Comment by whtiehack** [comment]
gcc 装好了吗？   你把报错贴出来呀

**Comment by whtiehack** [comment]
另外 有个10月14编译过的  https://github.com/whtiehack/wingui/releases

**Comment by lionios** [comment]
D:/liteide/bin/dlv.exe connect 127.0.0.1:58310 [E:/wingui-master/examples/wowjump]
API server listening at: 127.0.0.1:58310
could not launch process: fork/exec E:\wingui-master\examples\wowjump\wowjump.debug.exe: The application has failed to start because its side-by-side configuration is incorrect. Please see the application event log or use the command-line sxstrace.exe tool for more detail.

Dlv server exited with code 1
Dlv exited with code 1

**Comment by whtiehack** [comment]
dlv？   https://github.com/whtiehack/wingui/blob/master/examples/wowjump/build.bat  这有个简单编译脚本的

**Comment by lionios** [comment]
10月14那个我试过了，一样是提示没有找到WOW窗口，我怀疑是因为最近一次更新中将Wow.exe改成了WowClassic.exe导致的

**Comment by whtiehack** [comment]
不是通过 进程名称找的 

https://github.com/whtiehack/wingui/blob/f602d9a7e25aca28d162aa66f4169899a69dd9d0/examples/wowjump/multiwindows.go#L12-L28

**Comment by lionios** [comment]
直接运行你的bat会提示：
D:\Go\pkg\tool\windows_amd64\link.exe:running gcc failed: exit status 1
... ld.exe: i386 architecture of input file ... is incompatible with i386:x86-64 ouput collect2.exe: error: ld returned 1 exit status

**Comment by whtiehack** [comment]
你gcc装错了吧 装的32位的？

**Comment by lionios** [comment]
当前是TDM-GCC-64

第二次以为装错了重装了TDM-GCC-32，结果发现也不行，

第三次重新安装了TDM-GCC-64

**Comment by whtiehack** [comment]
`gcc --version` 看看

**Comment by lionios** [comment]
gcc <tdm64-1> 5.1.0

**Comment by lionios** [comment]
gcc <tdm64-1> 5.1.0

**Comment by lionios** [comment]
gcc tdm64-1 5.1.0

**Comment by whtiehack** [comment]
`gcc.exe (tdm64-1) 5.1.0`  
![image](https://user-images.githubusercontent.com/12741016/71318140-f5412300-24c7-11ea-9765-d1965b911e4f.png)
![image](https://user-images.githubusercontent.com/12741016/71318142-fa9e6d80-24c7-11ea-984a-8accb9cb4a79.png)

**Comment by lionios** [comment]
那我们是一样的，另我的操作系统是win7 64位 旗舰版 SP1

**Comment by whtiehack** [comment]
C:\Users\white>where gcc
D:\TDM-GCC-64\bin\gcc.exe

**Comment by whtiehack** [comment]
看看 `where gcc`

**Comment by lionios** [comment]
也和你一模一样

**Comment by whtiehack** [comment]
`go env` 看看

**Comment by lionios** [comment]
![image](https://user-images.githubusercontent.com/15306788/71318252-6d5c1880-24c9-11ea-9a9c-ff8fa99538e7.png)

**Comment by lionios** [comment]
![TIM截图20191222144333](https://user-images.githubusercontent.com/15306788/71318260-8fee3180-24c9-11ea-91d9-680ef3c04389.png)

这样你看得到吗？我不是很熟悉这个平台的图片上传功能

**Comment by lionios** [comment]
<img src='https://user-images.githubusercontent.com/15306788/71318260-8fee3180-24c9-11ea-91d9-680ef3c04389.png'></img>

**Comment by lionios** [comment]
set GO111MODULE=
set GOARCH=amd64
set GOBIN=
set GOCACHE=C:\Users\lx\AppData\Local\go-build
set GOENV=C:\Users\lx\AppData\Roaming\go\env
set GOEXE=.exe
set GOFLAGS=
set GOHOSTARCH=amd64
set GOHOSTOS=windows
set GONOPROXY=
set GONOSUMDB=
set GOOS=windows
set GOPATH=C:\Users\lx\go
set GOPRIVATE=
set GOPROXY=https://proxy.golang.org,direct
set GOROOT=D:\Go
set GOSUMDB=sum.golang.org
set GOTMPDIR=
set GOTOOLDIR=D:\Go\pkg\tool\windows_amd64
set GCCGO=gccgo
set AR=ar
set CC=gcc
set CXX=g++
set CGO_ENABLED=1
set GOMOD=
set CGO_CFLAGS=-g -O2
set CGO_CPPFLAGS=
set CGO_CXXFLAGS=-g -O2
set CGO_FFLAGS=-g -O2
set CGO_LDFLAGS=-g -O2
set PKG_CONFIG=pkg-config
set GOGCCFLAGS=-m64 -mthreads -fmessage-length=0 -fdebug-prefix-map=C:\User
AppData\Local\Temp\go-build993978250=/tmp/go-build -gno-record-gcc-switches

**Comment by whtiehack** [comment]
你按照 https://github.com/whtiehack/wingui/blob/master/examples/wowjump/build.bat  
一步一步执行 看看。把日志贴出来看看

**Comment by lionios** [comment]
E:\wingui-master\examples\wowjump>windres -i ui/ui.rc -O coff -o ui.syso

E:\wingui-master\examples\wowjump>set GOPROXY=https://goproxy.cn

E:\wingui-master\examples\wowjump>go generate
2019/12/22 14:59:52 genids filename ui/resource.h
2019/12/22 14:59:52 Match length  10
2019/12/22 14:59:52 gen ids finish

E:\wingui-master\examples\wowjump>go build -ldflags="-s -w -H windowsgui"
# github.com/whtiehack/wingui/examples/wowjump
D:\Go\pkg\tool\windows_amd64\link.exe: running gcc failed: exit status 1
D:/TDM-GCC-64/bin/../lib/gcc/x86_64-w64-mingw32/5.1.0/../../../../x86_64-w64-min
gw32/bin/ld.exe: i386 architecture of input file `C:\Users\lx\AppData\Local\Temp
\go-link-960573183\000000.o' is incompatible with i386:x86-64 output
collect2.exe: error: ld returned 1 exit status

**Comment by whtiehack** [comment]
![image](https://user-images.githubusercontent.com/12741016/71318547-28d27c00-24cd-11ea-9e9a-0cd2071f7082.png)
我这边无法复现啊。

:\Users\lx\AppData\Local\Temp
\go-link-960573183 
你把这个目录删除掉试试

**Comment by lionios** [comment]
我早就试过了，目标文件夹是个临时文件夹，每次我点进去之后根本找不到日志中提及的临时文件~

**Comment by lionios** [comment]
我顺便枚举了当前所有窗口的句柄，找不到GxWindowClass，这是不是意味着wow的窗口句柄已经变了？

**Comment by whtiehack** [comment]
那你看看 窗口类名变成什么了

**Comment by whtiehack** [comment]
![Uploading image.png…]()
我这边是没变的

**Comment by lionios** [comment]
我是写java的，我用java遍历出来的信息只有窗口名称，不知道是不是因为java的局限性。窗口名称是World of Warcraft。

另外我自己自用的电脑是win10，如果你的仍能够正常使用，不知道是不是因为win10获取句柄的限制不一样。

**Comment by whtiehack** [comment]
你找个窗口spy工具。看看 窗口的类名是什么。如果你装过visual studio的话，系统就自带一个 spy++

**Comment by lionios** [comment]
先从头捋一下，其实我一开始是自己用java写了一个用途和你的wowjump一样的小程序。但是这两天我发现java的虚拟按键（java.awt.Robot.keyPress）无法正确输送到wow了，所以找朋友要了你的wowjump，之后老是提示无法找到wow窗口迫使我开始研究go代码。

昨天之后，我在我的java小程序里加入了（com.sun.jna.platform.win32.User32.INSTANCE.FindWindow）检查成功找到GxWindowClass（我按你说的找了个窗口spy，确实没变），并用（com.sun.jna.platform.win32.User32.INSTANCE.SendInput）代替了java小程序原有的虚拟按键——但是SendInput再次失败了。

至于你的10月14版的wowjump，依然提示无法找到wow窗口……这两天的学习真是太奇幻了……

**Comment by lionios** [comment]
我现在决定重新回到解决如何在我的工作机（win7）上编译你的代码的思路上，wish me luck~

**Comment by lionios** [comment]
D:/liteide/bin/dlv.exe connect 127.0.0.1:65410 [E:/wingui-master/examples/wowjump]
API server listening at: 127.0.0.1:65410
unsupported architecture of windows/386 - only windows/amd64 is supported

Dlv server exited with code 1
Dlv error! 进程崩溃或运行终止
Dlv exited with code 62097

LiteIDE的报错居然跟昨天不一样了……

**Comment by lionios** [comment]
额~我用LiteIDE编译成功了！真是太神奇了……

**Comment by lionios** [comment]
我将
curh = winapi.FindWindowEx(0, curh, syscall.StringToUTF16Ptr("GxWindowClass"), nil)
修改成了
1.curh = winapi.FindWindowEx(0, curh, nil, syscall.StringToUTF16Ptr("魔兽世界"))//失败
2.curh = winapi.FindWindowEx(0, curh, nil, syscall.StringToUTF16Ptr("1.txt - 记事本"))//成功

这难道是win10的原因！？

**Comment by lionios** [comment]
2019/12/23 13:53:58 hwndArr [14877720 853766]

2019/12/23 13:53:58 select ret 0

2019/12/23 13:53:59 select ret 0

2019/12/23 13:53:59 没有找到WOW窗口

我开了两个窗口，发现其实hwnd里面是有东西的，但是他就是提示没有找到窗口……迷惑

**Comment by lionios** [comment]
r := win.MessageBox(hwnd, syscall.StringToUTF16Ptr("是否要操作这个WoW窗口?"),
			syscall.StringToUTF16Ptr("确认"), win.MB_YESNO)
		log.Println("select ret", r)
		c <- struct{}{}
		if r != win.IDYES {
			//continue//我把这句注释掉了，因为win10似乎调用不到MessageBox导致r的值永远无法满足这个if而被continue掉
		}

**Comment by lionios** [comment]
和我的最终猜想一样，在注释掉上面这个continue之后，你的wowjump已经可以在我的电脑上正常运行了，但是很遗憾，虚拟键盘指令/logout跟我的java程序一样无法传输到wow中。

感谢你昨天的抽空答复，这次学习又让我进步不少。

**Comment by whtiehack** [comment]
哦，明白你描述的问题所在了。晚上回家有空的话研究看看。

**Comment by whtiehack** [comment]
我朋友那边昨天还在用。我怀疑是不是权限问题。比如 wow用 管理员运行，工具用非管理员运行。这样可能会出现你说的情况。我猜的。

**Comment by lionios** [comment]
等我排队进去之后试试，另外我现在正在改用模拟鼠标分别点击菜单、返回人物选择、进入游戏这三个点来重现这个模型。

**Comment by lionios** [comment]
> 我朋友那边昨天还在用。我怀疑是不是权限问题。比如 wow用 管理员运行，工具用非管理员运行。这样可能会出现你说的情况。我猜的。

还真被你说中了，就仅仅只是简单的权限问题……当使用管理员权限运行wowjump之后，正常了……白瞎了我一通分析……

**Comment by lionios** [comment]
然后我发现了另一个……奇怪的问题，你说明上写着时间单位是秒，但我体感是毫秒……？

**Comment by whtiehack** [comment]
是秒呀。日志也有时间戳。
