### ISSUE TITLE
请问可以增加个屏幕大数字倒计时吗

### ISSUE THREAD

**Issue by touxinz** [whtiehack/wingui#8]
在最后那5-10秒 因为有时候挂机 是在电脑做其他事情 鼠标在作业  如果在最后几秒有个倒计时通知 美美的

**Comment by whtiehack** [comment]
小退时候我给工具窗口加个闪烁吧。 设置成选项给你。
![image](https://user-images.githubusercontent.com/12741016/74948222-f8f51580-5436-11ea-94d4-817f8de0ab0c.png)

**Comment by touxinz** [comment]
大神厉害👍




    


在2020年02月20日 23:16，smallwhite 写道： 小退时候我给工具窗口加个闪烁吧。 设置成选项给你。


—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/whtiehack/wingui/issues/8?email_source=notifications\u0026email_token=AOJLOZFJZ5REVU67VROPO5TRD2NEJA5CNFSM4KYMTKO2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMOQ3FA#issuecomment-589106580",
"url": "https://github.com/whtiehack/wingui/issues/8?email_source=notifications\u0026email_token=AOJLOZFJZ5REVU67VROPO5TRD2NEJA5CNFSM4KYMTKO2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMOQ3FA#issuecomment-589106580",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by whtiehack** [comment]
好了 下载去吧

**Comment by touxinz** [comment]
再次感谢！！！




    


在2020年02月20日 23:47，smallwhite 写道： 好了 下载去吧

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/whtiehack/wingui/issues/8?email_source=notifications\u0026email_token=AOJLOZDIUMJBIZQ6A4VUNY3RD2Q2HA5CNFSM4KYMTKO2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMO2Z6Y#issuecomment-589147387",
"url": "https://github.com/whtiehack/wingui/issues/8?email_source=notifications\u0026email_token=AOJLOZDIUMJBIZQ6A4VUNY3RD2Q2HA5CNFSM4KYMTKO2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOEMO2Z6Y#issuecomment-589147387",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]
